### PR TITLE
Add ability to choose what gestures to override

### PR DESCRIPTION
**Pull request by Sadhorsephile**
Resolves issue #18 (because allows to not override gestures using by interactive viewer)

### CODE REVIEW

**Comment by LauDijksterhuis** [comment]
Hello @Sadhorsephile ,

Before trying and editing my own fork, can you tell me if this solution fixes the problem where InteractiveViewer does not respond to input?

Thank you in advance.
Best regards,
Lau

**Comment by Sadhorsephile** [comment]
Hello @LauDijksterhui ,
In my case I couldn't use InteractiveViewer until I commented all gesture overrides apart from those I've used - (onTapDown and onTapUp).
I thought it was a good idea to give an opportunity to specify what gestures you want to override. So I've added the list to the constructor where it's possible to choose override gestures. All gestures are overrode as a default.

PS. It is my first PR, so sorry If I made any obvious for you mistake :) 

PPS. As far as I can see, the PR is shown in a repository of nateshmbhat and turned to the master branch of this particular repository.

Thank you for answer)

**Comment by nateshmbhat** [comment]
Thanks for your contributions. It would be helpful of u can add some comments for the override parameter so that users can know why they might wanna use this option

**Comment by jagomf** [comment]
@Sadhorsephile your solution can be helpful for many people. I think it is worth spending a little while on commenting a few lines on the new `gesturesToOverride` if this can end up being merged and published.

**Comment by jagomf** [comment]
@Sadhorsephile your solution can be helpful for many people. I think it is worth spending a little while on commenting a few lines on the new `gesturesToOverride` if this can end up being merged and published.

@nateshmbhat The longest this takes to merge, the more other people (like me) will switch from using the official package to forked repos...

**Review by nateshmbhat — APPROVED** [review]

**Comment by jagomf** [comment]
@nateshmbhat are you now planning to release a new touchable version anytime soon?

**Comment by jagomf** [comment]
@nateshmbhat are you planning to release a new touchable version anytime soon so that this feature can be used?

**Comment by jagomf** [comment]
@nateshmbhat are you planning to release a new touchable version anytime soon so that this feature can be used?

**Comment by jagomf** [comment]
@nateshmbhat are you planning to release a new touchable version anytime soon so that this feature can be used?

**Comment by jagomf** [comment]
@nateshmbhat are you planning to release a new touchable version anytime soon so that this feature can be used?

**Pull request merged**
