### PR TITLE
Using in scrollable widget

### PR DESCRIPTION
**Pull request by jja08111**
I'm using your awesome plugin in the scrollable widget. So I've made this PR.

I've added `scrollController`, `scrollDirection` parameter.

### CODE REVIEW

**Comment by nateshmbhat** [comment]
LGTM 
Thank you for your contributions :)

**Comment by nateshmbhat** [comment]
@jja08111 can you please add tests for this scrollable controller working ?

**Comment by jja08111** [comment]
> @jja08111 can you please add tests for this scrollable controller working?

Sorry, I don't know how to add tests, so it may take some time to learn how to do it. 
I will add tests after learning tests.

**Comment by nateshmbhat** [comment]
Alright 👍

**Pull request merged**
